"use client"

import { useStateContext } from "@/contexts/state-context"
import DestinationCard from "./destination-card"

export default function FeaturedDestinations() {
  const { selectedState } = useStateContext()

  const destinationsByState = {
    chhattisgarh: [
      {
        id: "chitrakote-falls",
        name: "Chitrakote Falls",
        location: "Bastar, Chhattisgarh",
        image: "/chitrakote.jpg",
        rating: 4.8,
        reviews: 1250,
        description: "Known as the 'Niagara of India', this spectacular waterfall is the widest in the country.",
        price: "₹2,500",
        duration: "2 Days",
        category: "waterfall",
      },
      {
        id: "sirpur",
        name: "Ancient Sirpur",
        location: "Mahasamund, Chhattisgarh",
        image: "/placeholder.svg?height=400&width=600&text=Sirpur+Heritage",
        rating: 4.6,
        reviews: 890,
        description: "Archaeological site with 1500-year-old Buddhist and Hindu temples.",
        price: "₹1,800",
        duration: "1 Day",
        category: "temple",
      },
      {
        id: "kanger-valley",
        name: "Kanger Valley National Park",
        location: "Bastar, Chhattisgarh",
        image: "/placeholder.svg?height=400&width=600&text=Kanger+Valley",
        rating: 4.7,
        reviews: 1100,
        description: "Dense forests, caves, and diverse wildlife in this pristine national park.",
        price: "₹3,200",
        duration: "3 Days",
        category: "national-park",
      },
    ],
    rajasthan: [
      {
        id: "jaipur-palace",
        name: "City Palace Jaipur",
        location: "Jaipur, Rajasthan",
        image: "/placeholder.svg?height=400&width=600&text=Jaipur+Palace",
        rating: 4.9,
        reviews: 2500,
        description: "Magnificent royal palace complex showcasing Rajasthani architecture.",
        price: "₹4,500",
        duration: "2 Days",
        category: "palace",
      },
      {
        id: "thar-desert",
        name: "Thar Desert Safari",
        location: "Jaisalmer, Rajasthan",
        image: "/placeholder.svg?height=400&width=600&text=Thar+Desert",
        rating: 4.8,
        reviews: 1800,
        description: "Experience golden sand dunes and traditional desert culture.",
        price: "₹6,000",
        duration: "3 Days",
        category: "desert",
      },
      {
        id: "udaipur-lakes",
        name: "Lake Palace Udaipur",
        location: "Udaipur, Rajasthan",
        image: "/placeholder.svg?height=400&width=600&text=Udaipur+Lake",
        rating: 4.9,
        reviews: 2200,
        description: "Floating marble palace on the serene Lake Pichola.",
        price: "₹8,500",
        duration: "2 Days",
        category: "palace",
      },
    ],
    kerala: [
      {
        id: "alleppey-backwaters",
        name: "Alleppey Backwaters",
        location: "Alleppey, Kerala",
        image: "/placeholder.svg?height=400&width=600&text=Alleppey+Backwaters",
        rating: 4.8,
        reviews: 3200,
        description: "Cruise through serene canals and coconut groves on traditional houseboats.",
        price: "₹5,500",
        duration: "2 Days",
        category: "backwaters",
      },
      {
        id: "munnar-hills",
        name: "Munnar Tea Gardens",
        location: "Munnar, Kerala",
        image: "/placeholder.svg?height=400&width=600&text=Munnar+Tea",
        rating: 4.7,
        reviews: 2800,
        description: "Rolling hills covered with lush green tea plantations.",
        price: "₹4,200",
        duration: "3 Days",
        category: "hills",
      },
      {
        id: "fort-kochi",
        name: "Historic Fort Kochi",
        location: "Kochi, Kerala",
        image: "/placeholder.svg?height=400&width=600&text=Fort+Kochi",
        rating: 4.6,
        reviews: 1900,
        description: "Colonial architecture and famous Chinese fishing nets.",
        price: "₹3,800",
        duration: "2 Days",
        category: "heritage",
      },
    ],
    himachal: [
      {
        id: "manali-valley",
        name: "Manali Valley",
        location: "Manali, Himachal Pradesh",
        image: "/placeholder.svg?height=400&width=600&text=Manali+Valley",
        rating: 4.8,
        reviews: 2100,
        description: "Snow-capped peaks, adventure sports, and scenic beauty.",
        price: "₹6,500",
        duration: "4 Days",
        category: "mountains",
      },
      {
        id: "dharamshala",
        name: "Dharamshala & McLeod Ganj",
        location: "Dharamshala, Himachal Pradesh",
        image: "/placeholder.svg?height=400&width=600&text=Dharamshala",
        rating: 4.7,
        reviews: 1600,
        description: "Tibetan culture, monasteries, and Himalayan views.",
        price: "₹4,800",
        duration: "3 Days",
        category: "spiritual",
      },
      {
        id: "spiti-valley",
        name: "Spiti Valley",
        location: "Spiti, Himachal Pradesh",
        image: "/placeholder.svg?height=400&width=600&text=Spiti+Valley",
        rating: 4.9,
        reviews: 1200,
        description: "Cold desert landscape with ancient monasteries.",
        price: "₹8,200",
        duration: "5 Days",
        category: "adventure",
      },
    ],
    goa: [
      {
        id: "old-goa-churches",
        name: "Old Goa Churches",
        location: "Old Goa, Goa",
        image: "/placeholder.svg?height=400&width=600&text=Old+Goa",
        rating: 4.6,
        reviews: 1400,
        description: "UNESCO World Heritage Portuguese colonial churches.",
        price: "₹2,800",
        duration: "1 Day",
        category: "heritage",
      },
      {
        id: "dudhsagar-falls",
        name: "Dudhsagar Falls",
        location: "Mollem, Goa",
        image: "/placeholder.svg?height=400&width=600&text=Dudhsagar+Falls",
        rating: 4.7,
        reviews: 1800,
        description: "Spectacular four-tiered waterfall in lush Western Ghats.",
        price: "₹3,500",
        duration: "1 Day",
        category: "waterfall",
      },
      {
        id: "goa-beaches",
        name: "Goa Beach Circuit",
        location: "North & South Goa",
        image: "/placeholder.svg?height=400&width=600&text=Goa+Beaches",
        rating: 4.8,
        reviews: 3500,
        description: "Golden beaches, water sports, and vibrant nightlife.",
        price: "₹4,500",
        duration: "3 Days",
        category: "beach",
      },
    ],
    "tamil-nadu": [
      {
        id: "meenakshi-temple",
        name: "Meenakshi Temple",
        location: "Madurai, Tamil Nadu",
        image: "/placeholder.svg?height=400&width=600&text=Meenakshi+Temple",
        rating: 4.9,
        reviews: 2800,
        description: "Magnificent Dravidian temple with intricate sculptures and towering gopurams.",
        price: "₹3,200",
        duration: "2 Days",
        category: "temple",
      },
      {
        id: "ooty-hills",
        name: "Ooty Hill Station",
        location: "Ooty, Tamil Nadu",
        image: "/placeholder.svg?height=400&width=600&text=Ooty+Hills",
        rating: 4.7,
        reviews: 2400,
        description: "Queen of Hill Stations with tea gardens and colonial charm.",
        price: "₹5,200",
        duration: "3 Days",
        category: "hills",
      },
      {
        id: "mahabalipuram",
        name: "Mahabalipuram Shore Temple",
        location: "Mahabalipuram, Tamil Nadu",
        image: "/placeholder.svg?height=400&width=600&text=Shore+Temple",
        rating: 4.8,
        reviews: 1900,
        description: "Ancient rock-cut temples and sculptures by the Bay of Bengal.",
        price: "₹2,800",
        duration: "1 Day",
        category: "heritage",
      },
    ],
    karnataka: [
      {
        id: "mysore-palace",
        name: "Mysore Palace",
        location: "Mysore, Karnataka",
        image: "/placeholder.svg?height=400&width=600&text=Mysore+Palace",
        rating: 4.8,
        reviews: 3100,
        description: "Opulent royal palace with Indo-Saracenic architecture and grandeur.",
        price: "₹3,800",
        duration: "2 Days",
        category: "palace",
      },
      {
        id: "hampi-ruins",
        name: "Hampi Historical Ruins",
        location: "Hampi, Karnataka",
        image: "/placeholder.svg?height=400&width=600&text=Hampi+Ruins",
        rating: 4.9,
        reviews: 2600,
        description: "UNESCO World Heritage site with Vijayanagara Empire ruins.",
        price: "₹4,200",
        duration: "3 Days",
        category: "heritage",
      },
      {
        id: "coorg-coffee",
        name: "Coorg Coffee Estates",
        location: "Coorg, Karnataka",
        image: "/placeholder.svg?height=400&width=600&text=Coorg+Coffee",
        rating: 4.7,
        reviews: 2200,
        description: "Scotland of India with lush coffee plantations and misty hills.",
        price: "₹4,800",
        duration: "3 Days",
        category: "nature",
      },
    ],
    maharashtra: [
      {
        id: "ajanta-caves",
        name: "Ajanta Caves",
        location: "Aurangabad, Maharashtra",
        image: "/placeholder.svg?height=400&width=600&text=Ajanta+Caves",
        rating: 4.9,
        reviews: 3500,
        description: "UNESCO World Heritage Buddhist cave paintings and sculptures.",
        price: "₹3,500",
        duration: "2 Days",
        category: "heritage",
      },
      {
        id: "ellora-caves",
        name: "Ellora Caves",
        location: "Aurangabad, Maharashtra",
        image: "/placeholder.svg?height=400&width=600&text=Ellora+Caves",
        rating: 4.8,
        reviews: 3200,
        description: "Multi-religious rock-cut temple complex with Kailasa Temple.",
        price: "₹3,800",
        duration: "2 Days",
        category: "heritage",
      },
      {
        id: "lonavala-hills",
        name: "Lonavala Hill Station",
        location: "Lonavala, Maharashtra",
        image: "/placeholder.svg?height=400&width=600&text=Lonavala+Hills",
        rating: 4.6,
        reviews: 2800,
        description: "Scenic hill station with valleys, caves, and monsoon beauty.",
        price: "₹4,200",
        duration: "2 Days",
        category: "hills",
      },
    ],
    "madhya-pradesh": [
      {
        id: "khajuraho-temples",
        name: "Khajuraho Temples",
        location: "Khajuraho, Madhya Pradesh",
        image: "/placeholder.svg?height=400&width=600&text=Khajuraho+Temples",
        rating: 4.9,
        reviews: 2900,
        description: "UNESCO World Heritage temples with exquisite erotic sculptures.",
        price: "₹4,500",
        duration: "2 Days",
        category: "heritage",
      },
      {
        id: "bandhavgarh",
        name: "Bandhavgarh National Park",
        location: "Umaria, Madhya Pradesh",
        image: "/placeholder.svg?height=400&width=600&text=Bandhavgarh+Tigers",
        rating: 4.8,
        reviews: 2100,
        description: "Famous tiger reserve with highest density of tigers in India.",
        price: "₹6,500",
        duration: "3 Days",
        category: "wildlife",
      },
      {
        id: "sanchi-stupa",
        name: "Sanchi Stupa",
        location: "Sanchi, Madhya Pradesh",
        image: "/placeholder.svg?height=400&width=600&text=Sanchi+Stupa",
        rating: 4.7,
        reviews: 1800,
        description: "Ancient Buddhist monument and UNESCO World Heritage site.",
        price: "₹2,800",
        duration: "1 Day",
        category: "heritage",
      },
    ],
    odisha: [
      {
        id: "jagannath-temple",
        name: "Jagannath Temple",
        location: "Puri, Odisha",
        image: "/placeholder.svg?height=400&width=600&text=Jagannath+Temple",
        rating: 4.8,
        reviews: 3800,
        description: "Sacred Hindu temple and one of the Char Dham pilgrimage sites.",
        price: "₹3,200",
        duration: "2 Days",
        category: "temple",
      },
      {
        id: "konark-temple",
        name: "Konark Sun Temple",
        location: "Konark, Odisha",
        image: "/placeholder.svg?height=400&width=600&text=Konark+Sun+Temple",
        rating: 4.9,
        reviews: 2600,
        description: "UNESCO World Heritage temple designed as a colossal chariot.",
        price: "₹2,800",
        duration: "1 Day",
        category: "heritage",
      },
      {
        id: "chilika-lake",
        name: "Chilika Lake",
        location: "Puri, Odisha",
        image: "/placeholder.svg?height=400&width=600&text=Chilika+Lake",
        rating: 4.7,
        reviews: 2200,
        description: "Asia's largest brackish water lagoon with migratory birds.",
        price: "₹3,800",
        duration: "2 Days",
        category: "nature",
      },
    ],
    jharkhand: [
      {
        id: "hundru-falls",
        name: "Hundru Falls",
        location: "Ranchi, Jharkhand",
        image: "/placeholder.svg?height=400&width=600&text=Hundru+Falls",
        rating: 4.7,
        reviews: 1800,
        description: "Spectacular 320-foot waterfall surrounded by dense forests.",
        price: "₹2,500",
        duration: "1 Day",
        category: "waterfall",
      },
      {
        id: "betla-national-park",
        name: "Betla National Park",
        location: "Latehar, Jharkhand",
        image: "/placeholder.svg?height=400&width=600&text=Betla+National+Park",
        rating: 4.6,
        reviews: 1400,
        description: "Tiger reserve with diverse wildlife and ancient fort ruins.",
        price: "₹4,200",
        duration: "2 Days",
        category: "wildlife",
      },
      {
        id: "deoghar-temple",
        name: "Baidyanath Temple",
        location: "Deoghar, Jharkhand",
        image: "/placeholder.svg?height=400&width=600&text=Baidyanath+Temple",
        rating: 4.8,
        reviews: 2400,
        description: "Sacred Jyotirlinga temple and major pilgrimage destination.",
        price: "₹2,800",
        duration: "2 Days",
        category: "temple",
      },
    ],
    "andhra-pradesh": [
      {
        id: "tirupati-temple",
        name: "Tirupati Balaji Temple",
        location: "Tirupati, Andhra Pradesh",
        image: "/placeholder.svg?height=400&width=600&text=Tirupati+Temple",
        rating: 4.9,
        reviews: 4500,
        description: "World's most visited Hindu temple dedicated to Lord Venkateswara.",
        price: "₹3,500",
        duration: "2 Days",
        category: "temple",
      },
      {
        id: "araku-valley",
        name: "Araku Valley",
        location: "Visakhapatnam, Andhra Pradesh",
        image: "/placeholder.svg?height=400&width=600&text=Araku+Valley",
        rating: 4.7,
        reviews: 2200,
        description: "Hill station with coffee plantations and tribal culture.",
        price: "₹4,800",
        duration: "3 Days",
        category: "hills",
      },
      {
        id: "belum-caves",
        name: "Belum Caves",
        location: "Kurnool, Andhra Pradesh",
        image: "/placeholder.svg?height=400&width=600&text=Belum+Caves",
        rating: 4.6,
        reviews: 1600,
        description: "India's longest cave system with stunning stalactite formations.",
        price: "₹2,800",
        duration: "1 Day",
        category: "caves",
      },
    ],
  }

  const destinations =
    destinationsByState[selectedState.id as keyof typeof destinationsByState] || destinationsByState.chhattisgarh

  return (
    <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 lg:gap-8">
      {destinations.map((destination) => (
        <DestinationCard key={destination.id} {...destination} />
      ))}
    </div>
  )
}
